const int HIVE_TYPE_ID_GLOBAL_VO = 1;
const int HIVE_TYPE_ID_SUMMARY_COUNTRY_VO = 2;
const int HIVE_TYPE_ID_PREMIUM_VO = 3;
const int HIVE_TYPE_ID_SUMMARY_RESPONSE = 4;
const int HIVE_TYPE_ID_COUNTRY_VO = 5;

const String BOX_NAME_GLOBAL_VO = "BOX_NAME_GLOBAL_VO";
const String BOX_NAME_SUMMARY_COUNTRY_VO = "BOX_NAME_SUMMARY_COUNTRY_VO";
const String BOX_NAME_PREMIUM_VO = "BOX_NAME_PREMIUM_VO";
const String BOX_NAME_SUMMARY_RESPONSE = "BOX_NAME_SUMMARY_RESPONSE";
const String BOX_NAME_COUNTRY_VO = "BOX_NAME_COUNTRY_VO";